DROP TABLE tblexcursion_services_quotedetails;
DROP TABLE tblexcursion_services_quotedetails_paxbreaks;
DROP TABLE tblexcursion_services_rates_countries;
DROP TABLE tblexcursion_services_rates_to;
DROP TABLE tblexcursion_services_rates_ratestype;
DROP TABLE tblexcursion_services_rates_insertclosedate;
DROP TABLE tblexcursion_services_rates_insertrates;
DROP TABLE tblexcursion_services;