/* BOOKING SYSTEM */

/* BOOKING DOSSIER */
CREATE TABLE `booking` (
  `id_booking` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_quote` int(11) NOT NULL DEFAULT 0 COMMENT 'id_quote from quote table',
  `to_ref` varchar(15) NOT NULL DEFAULT '0' COMMENT 'Booking code of the TO',
  `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
  `id_country` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblcountries',
  `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
  `booking_for` varchar(50) NOT NULL DEFAULT '' COMMENT 'Name of Booking Client to appear on dossier',
  `pax_type` varchar(50) NOT NULL DEFAULT '' COMMENT 'PAX type Standard/Honneymoon/Wedding',
  `booking_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'First arrival date of client',
  `booking_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Last departure date of client',
  `adult_amt` int(11) DEFAULT 0 COMMENT 'no of adult',
  `teen_amt` int(11) DEFAULT 0 COMMENT 'no of teen',
  `child_amt` int(11) DEFAULT 0 COMMENT 'no of child',
  `infant_amt` int(11) DEFAULT 0 COMMENT 'no of infant',
  `opt_date` date DEFAULT '9999-12-31' COMMENT 'date after which dossier can be invoiced',
  `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
  `created_name` varchar(250) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
  `remarks` text DEFAULT NULL COMMENT 'remarks for the booking',
  `status` varchar(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
  `invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
  `invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
  `close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
  `close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
  PRIMARY KEY (`id_booking`),
  KEY `id_quotefk` (`id_quote`),
  KEY `id_TOfk` (`id_tour_operator`),
  KEY `id_countryfk` (`id_country`),
  KEY `id_deptfk` (`id_dept`),
  KEY `booking_from` (`booking_from`),
  KEY `booking_to` (`booking_to`),
  KEY `created_by` (`created_by`),
  KEY `status` (`status`),
  KEY `close` (`close`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_log` (
  `id_booking_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_booking` int(11) NOT NULL COMMENT 'id_booking from booking table',
  `id_quote` int(11) NOT NULL DEFAULT 0 COMMENT 'id_quote from quote table',
  `to_ref` varchar(15) NOT NULL DEFAULT '0' COMMENT 'Booking code of the TO',
  `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
  `id_country` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblcountries',
  `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
  `booking_for` varchar(50) NOT NULL DEFAULT '' COMMENT 'Name of Booking Client to appear on dossier',
  `pax_type` varchar(50) NOT NULL DEFAULT '' COMMENT 'PAX type Standard/Honneymoon/Wedding',
  `booking_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'First arrival date of client',
  `booking_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Last departure date of client',
  `adult_amt` int(11) DEFAULT 0 COMMENT 'no of adult',
  `teen_amt` int(11) DEFAULT 0 COMMENT 'no of teen',
  `child_amt` int(11) DEFAULT 0 COMMENT 'no of child',
  `infant_amt` int(11) DEFAULT 0 COMMENT 'no of infant',
  `opt_date` date DEFAULT '9999-12-31' COMMENT 'date after which dossier can be invoiced',
  `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
  `created_name` varchar(50) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
  `remarks` text DEFAULT NULL COMMENT 'remarks for the booking',
  `status` varchar(25) NOT NULL DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
  `invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
  `invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
  `close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
  `close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
  `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
  `uname` varchar(45) NOT NULL DEFAULT 'NONE',
  `log_date` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
  PRIMARY KEY (`id_booking_log`),
  KEY `id_bookingfk` (`id_booking`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/*  CLIENT */

CREATE TABLE `client` (
  `id_client` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `type` varchar(7) NOT NULL DEFAULT 'ADULT' COMMENT 'Type of client ADULT/TEEN/CHILD/INFANT',
  `is_vip` int(2) NOT NULL DEFAULT 0 COMMENT '1 = VIP/ 0= NOT VIP',
  `title` varchar(10) NOT NULL DEFAULT '' COMMENT 'Client title MR/MRS/MS/MISS/SIR/LADY',
  `surname` varchar(500) NOT NULL DEFAULT '' COMMENT 'Client surname',
  `other_name` varchar(500) NOT NULL DEFAULT '' COMMENT 'Client othername',
  `client_dob` date DEFAULT NULL COMMENT 'Date of birth of client',
  `passport_no` varchar(11) DEFAULT '' COMMENT 'Passport no of client',
  `remarks` varchar(250) DEFAULT '' COMMENT 'Remarks',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active 0 for deleted',
  PRIMARY KEY (`id_client`),
  KEY `surname` (`surname`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;


CREATE TABLE `client_log` (
  `id_client_log` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_client` INT(11) NOT NULL COMMENT 'id from client table',
  `type` VARCHAR(7) NOT NULL DEFAULT 'ADULT' COMMENT 'Type of client ADULT/TEEN/CHILD/INFANT',
  `is_vip` SMALLINT(1)  NOT NULL DEFAULT 0 COMMENT '1 = VIP/ 0= NOT VIP',
  `title` VARCHAR(10) NOT NULL DEFAULT '' COMMENT 'Client title MR/MRS/MS/MISS/SIR/LADY',
  `surname` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Client surname',
  `other_name` VARCHAR(500) NOT NULL DEFAULT '' COMMENT 'Client othername',
  `client_dob` DATE DEFAULT '9999-12-31' COMMENT 'Date of birth of client',
  `passport_no` VARCHAR(11) DEFAULT NULL COMMENT 'Passport no of client',
  `remarks` VARCHAR(250) DEFAULT '' COMMENT 'Remarks',
  `id_user` INT(11) NOT NULL COMMENT 'id from tbluser',
  `uname` VARCHAR(45) NOT NULL DEFAULT 'NONE',
  `log_date` DATETIME NOT NULL DEFAULT '9999-12-31 00:00:01',
  `log_status` VARCHAR(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
  PRIMARY KEY (`id_client_log`),
  KEY `id_clientfk` (`id_client`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `booking_client` (
  `id_booking_client` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_client` int(11) NOT NULL COMMENT 'id_booking from client table',
  `id_booking` int(11) NOT NULL COMMENT 'id_booking from booking table',
  `id_quote` int(11) NOT NULL COMMENT 'id_quote from quote table',
  `age` int(11) DEFAULT NULL COMMENT 'client age',
  `yearMonth` varchar(15) NOT NULL DEFAULT '' COMMENT 'Year or Month',
  `remarks` varchar(250) DEFAULT '' COMMENT 'Remarks',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active 0 for deleted',
  PRIMARY KEY (`id_booking_client`),
  KEY `id_clientfk` (`id_client`),
  KEY `id_bookingfk` (`id_booking`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_client_log` (
  `id_booking_client_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_booking_client` int(11) NOT NULL COMMENT 'id_booking_client from booking_client',
  `id_client` int(11) NOT NULL COMMENT 'id_booking from client table',
  `id_booking` int(11) NOT NULL COMMENT 'id_booking from booking table',
  `id_quote` int(11) NOT NULL COMMENT 'id_quote from quote table',
  `age` int(11) DEFAULT NULL COMMENT 'client age',
  `yearMonth` varchar(15) NOT NULL DEFAULT '' COMMENT 'Year or Month',
  `remarks` varchar(250) DEFAULT '' COMMENT 'Remarks',
  `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
  `uname` varchar(45) NOT NULL DEFAULT '',
  `log_date` datetime NOT NULL DEFAULT '9999-12-31 00:00:01',
  `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
  PRIMARY KEY (`id_booking_client_log`),
  KEY `id_booking_clientfk` (`id_booking_client`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `booking_activity`;
DROP TABLE IF EXISTS `booking_activity_log`;
DROP TABLE IF EXISTS `booking_activity_client`;

DROP TABLE IF EXISTS `booking_activity`;
DROP TABLE IF EXISTS `booking_activity_log`;

/*  ACTIVITY */
CREATE TABLE `booking_activity_claim` (
  `id_booking_activity_claim` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
  `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
  `activity_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
  `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
  `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
  `activity_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date of activity',
  `activity_time` time DEFAULT NULL COMMENT 'time of activity',
  `activity_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
  `id_product` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product from product table',
  `id_product_service` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service from product_service table',
  `activity_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'descriptive name of the activity',
  `activity_duration` time(5) DEFAULT NULL COMMENT 'Duration of service',
  `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
  `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
  `activity_pickup_time` time DEFAULT NULL COMMENT 'time if transfer included in activity',
  `activity_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the activity',
  `activity_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the activity',
  `activity_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the activity',
  `activity_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the activity',
  `activity_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the activity',
  `id_product_service_claim` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_claim from product_service_claim table',
  `id_product_service_claim_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from ???? table',
  `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
  `activity_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
  `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of activity',
  `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
  `activity_adult_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim excluding TAX',
  `activity_adult_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim',
  `activity_teen_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim excluding TAX',
  `activity_teen_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim',
  `activity_child_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim excluding TAX',
  `activity_child_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim',
  `activity_infant_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim excluding TAX',
  `activity_infant_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim',
  `activity_total_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim excluding TAX',
  `activity_total_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim',
  `activity_rebate_claim_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
  `activity_rebate_claim_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
  `activity_discount_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
  `activity_adult_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
  `activity_adult_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount excluding TAX',
  `activity_adult_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount',
  `activity_teen_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
  `activity_teen_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount',
  `activity_teen_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount excluding TAX',
  `activity_child_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
  `activity_child_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount',
  `activity_child_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount excluding TAX',
  `activity_infant_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
  `activity_infant_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount',
  `activity_infant_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount excluding TAX',
  `activity_total_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount excluding TAX',
  `activity_total_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount',
  `activity_client_room_no` varchar(25) DEFAULT NULL COMMENT 'room no of the client for the activity',
  `id_language` int(11) NOT NULL DEFAULT 0 COMMENT 'id from language',
  `id_rep` int(11) DEFAULT NULL COMMENT 'id_rep from representative table',
  `activity_voucher_no` varchar(15) NOT NULL DEFAULT '' COMMENT 'voucher no of activity if on direct sale',
  `activity_remarks` text DEFAULT NULL COMMENT 'remarks for the activity booking',
  `activity_internal_remarks` text DEFAULT NULL COMMENT 'internal remarks for the acoom booking',
  `activity_invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
  `activity_invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
  `activity_close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
  `activity_close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
  `activity_status` varchar(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
  `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
  `created_name` varchar(25) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
  PRIMARY KEY (`id_booking_activity_claim`),
  KEY `id_bookingfk` (`id_booking`),
  KEY `id_tour_operatorfk` (`id_tour_operator`),
  KEY `id_productfk` (`id_product`),
  KEY `id_product_servicefk` (`id_product_service`),
  KEY `id_hotelfk` (`id_hotel`),
  KEY `id_product_service_claimfk` (`id_product_service_claim`),
  KEY `id_languagefk` (`id_language`),
  KEY `activity_invoice_no` (`activity_invoice_no`),
  KEY `activity_close` (`activity_close`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_activity_cost` (
  `id_booking_activity_cost` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
  `id_booking_activity_claim` int(11) NOT NULL COMMENT 'id_booking_activity from table booking_activity_claim',
  `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
  `id_product` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product from product table',
  `id_product_service` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service from product_service table',
  `id_product_service_claim` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_claim from product_service_claim table',
  `id_product_service_cost` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_cost from product_service_cost table',
  `id_product_service_cost_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from ???? table',
  `activity_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the activity',
  `activity_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the activity',
  `activity_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the activity',
  `activity_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the activity',
  `activity_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the activity',
  `activity_adult_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost',
  `activity_teen_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost',
  `activity_child_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost',
  `activity_infant_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost',
  `activity_total_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost',
  `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
  `created_name` varchar(25) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
  PRIMARY KEY (`id_booking_activity_cost`),
  KEY `id_bookingfk` (`id_booking`),
  KEY `id_productfk` (`id_product`),
  KEY `id_product_servicefk` (`id_product_service`),
  KEY `id_product_service_claimfk` (`id_product_service_claim`),
  KEY `id_product_service_costfk` (`id_product_service_cost`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_activity_client` (
  `id_booking_activity_client` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
  `id_client` int(11) NOT NULL COMMENT 'id_client from client table',
  `id_booking_activity_claim` int(11) NOT NULL COMMENT 'id_booking_activity from booking_activity table',
  `id_booking` int(11) NOT NULL COMMENT 'id_booking from booking table',
  `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active 0 for deleted',
  PRIMARY KEY (`id_booking_activity_client`),
  KEY `id_clientfk` (`id_client`),
  KEY `id_booking_activityfk` (`id_booking_activity_claim`),
  KEY `id_bookingfk` (`id_booking`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_activity_claim_log` (
  `id_booking_activity_claim_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
  `id_booking_activity_claim` int(11) NOT NULL COMMENT 'id_booking_activity_claim from id_booking_activity_claim',
  `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
  `activity_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
  `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
  `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
  `activity_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date of activity',
  `activity_time` time DEFAULT NULL COMMENT 'time of activity',
  `activity_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
  `id_product` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product from product table',
  `id_product_service` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service from product_service table',
  `activity_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT 'descriptive name of the activity',
  `activity_duration` time(5) DEFAULT NULL COMMENT 'Duration of service',
  `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
  `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
  `activity_pickup_time` time DEFAULT NULL COMMENT 'time if transfer included in activity',
  `activity_clients` varchar(255) NOT NULL DEFAULT '0' COMMENT 'id_clients from booking_activity_client',
  `activity_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the activity',
  `activity_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the activity',
  `activity_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the activity',
  `activity_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the activity',
  `activity_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the activity',
  `id_product_service_claim` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_claim from product_service_claim table',
  `id_product_service_claim_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from ???? table',
  `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
  `activity_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
  `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of activity',
  `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
  `activity_adult_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim excluding TAX',
  `activity_adult_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim',
  `activity_teen_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim excluding TAX',
  `activity_teen_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim',
  `activity_child_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim excluding TAX',
  `activity_child_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim',
  `activity_infant_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim excluding TAX',
  `activity_infant_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim',
  `activity_total_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim excluding TAX',
  `activity_total_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim',
  `activity_rebate_claim_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
  `activity_rebate_claim_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
  `activity_discount_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
  `activity_adult_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
  `activity_adult_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount excluding TAX',
  `activity_adult_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount',
  `activity_teen_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
  `activity_teen_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount excluding TAX',
  `activity_teen_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount',
  `activity_child_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
  `activity_child_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount',
  `activity_child_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount excluding TAX',
  `activity_infant_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
  `activity_infant_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount',
  `activity_infant_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount excluding TAX',
  `activity_total_claim_after_disc_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount excluding TAX',
  `activity_total_claim_after_disc` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount',
  `activity_client_room_no` varchar(25) DEFAULT NULL COMMENT 'room no of the client for the activity',
  `id_language` int(11) NOT NULL DEFAULT 0 COMMENT 'id from language',
  `id_rep` int(11) DEFAULT NULL COMMENT 'id_rep from representative table',
  `activity_voucher_no` varchar(15) NOT NULL DEFAULT '' COMMENT 'voucher no of activity if on direct sale',
  `activity_remarks` varchar(25) DEFAULT NULL COMMENT 'remarks for the activity booking',
  `activity_internal_remarks` varchar(25) DEFAULT NULL COMMENT 'internal remarks for the acoom booking',
  `activity_invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
  `activity_invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
  `activity_close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
  `activity_close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
  `activity_status` varchar(25) COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
  `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
  `uname` varchar(45) NOT NULL DEFAULT 'NONE',
  `log_date` datetime NOT NULL DEFAULT current_timestamp(),
  `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
  PRIMARY KEY (`id_booking_activity_claim_log`),
  KEY `id_booking_activity_claimfk` (`id_booking_activity_claim`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

CREATE TABLE `booking_activity_cost_log` (
  `id_booking_activity_cost_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
  `id_booking_activity_cost` int(11) NOT NULL COMMENT 'id_booking_activity_cost from booking_activity_cost',
  `id_booking_activity_claim` int(11) NOT NULL COMMENT 'id_booking_activity from table booking_activity_claim',
  `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
  `id_product` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product from product table',
  `id_product_service` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service from product_service table',
  `id_product_service_claim` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_claim from product_service_claim table',
  `id_product_service_cost` int(11) NOT NULL DEFAULT 0 COMMENT 'id_product_service_cost from product_service_cost table',
  `id_product_service_cost_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from ???? table',
  `activity_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the activity',
  `activity_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the activity',
  `activity_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the activity',
  `activity_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the activity',
  `activity_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the activity',
  `activity_adult_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost',
  `activity_teen_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost',
  `activity_child_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost',
  `activity_infant_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost',
  `activity_total_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost',
  `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
  `uname` varchar(45) NOT NULL DEFAULT 'NONE',
  `log_date` datetime NOT NULL DEFAULT current_timestamp(),
  `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
  PRIMARY KEY (`id_booking_activity_cost_log`),
  KEY `id_booking_activity_cost` (`id_booking_activity_cost`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* TAX RATE */
CREATE TABLE `tax_rate` (
  `id_tax_rate` int(11) NOT NULL AUTO_INCREMENT,
  `id_tax_code` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltaxcodes',
  `tx_code` varchar(30) DEFAULT NULL COMMENT 'tx_code from tbltaxcodes',
  `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'vat value applied',
  `tax_dateFrom` date DEFAULT NULL COMMENT 'Date period start of Tax applied',
  `tax_dateTo` date DEFAULT NULL COMMENT 'Date period end of Tax applied',
  `active` smallint(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_tax_rate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `tax_rate` (`id_tax_rate`, `id_tax_code`, `tx_code`, `tax_value`, `tax_dateFrom`, `tax_dateTo`, `active`)
VALUES
	(1,3,'VAT',12.00,'1992-01-01','1998-06-30',1),
	(2,3,'VAT',15.00,'1998-07-01',NULL,1);

-- Insert menu
    INSERT INTO `tblmenu` (`menuid`, `menuname`, `parentfk`, `leaf`, `ordering`, `icon`, `clkevent`, `menusysid`, `description`, `inout`)
VALUES
    (58, 'Booking System', 2, 'Y', 3, 'fas fa-briefcase', '', 'bookingSystem', 'Booking System', 'O');


    CREATE TABLE `booking_room` (
      `id_booking_room` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `stay_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `stay_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_status` VARCHAR(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
      `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
      `created_name` varchar(25) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
      `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
      PRIMARY KEY (`id_booking_room`)
    ) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_log` (
      `id_booking_room_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `id_booking_room` INT(11) NOT NULL COMMENT 'id_booking_room from ibooking_room',
      `stay_from` DATE NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `stay_to` DATE NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_adult_amt` INT(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` INT(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` INT(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` INT(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_status` varchar(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
      `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
      `uname` varchar(45) NOT NULL DEFAULT 'NONE',
      `log_date` datetime NOT NULL DEFAULT current_timestamp(),
      `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
      PRIMARY KEY (`id_booking_room_log`),
      KEY `id_booking_room` (`id_booking_room`)
    ) ENGINE=INNODB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_claim` (
      `id_booking_room_claim` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from booking table',
      `id_booking_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking_room from booking_room table to regroup line of accom',
      `room_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
      `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
      `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
      `room_stay_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `room_stay_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
      `id_contract` int(11) NOT NULL DEFAULT 0 COMMENT 'id_contract from tblservice_contract table',
      `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
      `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
      `id_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels_rooms table ????',
      `room_details` varchar(255) NOT NULL DEFAULT 0 COMMENT 'room choosen with occupancy and meal plan',
      `service_details` varchar(30) NOT NULL DEFAULT 'TARIFF' COMMENT 'TARIFFF = room initial tariff / OFFER = room SPO / SHARING = sharing tariff / SUPPLEMENT = additional supplement',
      `room_claim_calcultation` text DEFAULT NULL COMMENT 'claim calculation',
      `room_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the room',
      `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
      `room_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
      `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of room',
      `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
      `id_claim_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from tblcurrency table',
      `room_adult_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim excluding TAX',
      `room_adult_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim',
      `room_teen_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim excluding TAX',
      `room_teen_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim',
      `room_child_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim excluding TAX',
      `room_child_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim',
      `room_infant_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim excluding TAX',
      `room_infant_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim',
      `room_total_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim excluding TAX',
      `room_total_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim',
      `room_rebate_claim_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
      `room_rebate_claim_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
      `room_rebate_claim_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
      `room_adult_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
      `room_adult_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount excluding TAX',
      `room_adult_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount',
      `room_teen_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
      `room_teen_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount',
      `room_teen_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount excluding TAX',
      `room_child_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
      `room_child_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount',
      `room_child_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount excluding TAX',
      `room_infant_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
      `room_infant_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount',
      `room_infant_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount excluding TAX',
      `room_total_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount excluding TAX',
      `room_total_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount',
      `room_remarks` text DEFAULT NULL COMMENT 'room for the activity booking',
      `room_internal_remarks` text DEFAULT NULL COMMENT 'room for the activity booking',
      `room_invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
      `room_invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
      `room_close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
      `room_close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
      `room_status` varchar(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
      `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
      `created_name` varchar(25) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
      `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
      PRIMARY KEY (`id_booking_room_claim`),
      KEY `id_bookingfk` (`id_booking`),
      KEY `id_tour_operatorfk` (`id_tour_operator`),
      KEY `id_contractfk` (`id_contract`),
      KEY `id_hotelfk` (`id_hotel`),
      KEY `id_roomfk` (`id_room`),
      KEY `id_service_taxfk` (`id_service_tax`),
      KEY `room_invoice_no` (`room_invoice_no`),
      KEY `room_close` (`room_close`)
    ) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_client` (
      `id_booking_room_client` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment field',
      `id_client` int(11) NOT NULL COMMENT 'id_client from client table',
      `id_booking_room_claim` int(11) NOT NULL COMMENT 'id_booking_room_claim from booking_room_claim table',
      `id_booking` int(11) NOT NULL COMMENT 'id_booking from booking table',
      `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active 0 for deleted',
      PRIMARY KEY (`id_booking_room_client`),
      KEY `id_clientfk` (`id_client`),
      KEY `id_booking_room_claimfk` (`id_booking_room_claim`),
      KEY `id_bookingfk` (`id_booking`)
    ) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_cost` (
      `id_booking_room_cost` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `id_booking_room_claim` int(11) NOT NULL COMMENT 'id_booking_room_claim from booking_room_claim',
      `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
      `id_booking_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking_room from booking_room table to regroup line of accom',
      `room_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
      `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
      `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
      `room_stay_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `room_stay_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
      `id_contract` int(11) NOT NULL DEFAULT 0 COMMENT 'id_contract from tblservice_contract table',
      `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
      `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
      `id_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels_rooms table ????',
      `room_details` varchar(255) NOT NULL DEFAULT 0 COMMENT 'room choosen with occupancy and meal plan',
      `service_details` varchar(30) NOT NULL DEFAULT 'TARIFF' COMMENT 'TARIFFF = room initial tariff / OFFER = room SPO / SHARING = sharing tariff / SUPPLEMENT = additional supplement',
      `room_cost_calcultation` text DEFAULT NULL COMMENT 'room choosen with occupancy and meal plan',
      `room_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the room',
      `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
      `room_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
      `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of room',
      `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
      `id_cost_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from tblcurrency table',
      `room_adult_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial cost excluding TAX',
      `room_adult_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial cost',
      `room_teen_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial cost excluding TAX',
      `room_teen_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial cost',
      `room_child_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial cost excluding TAX',
      `room_child_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial cost',
      `room_infant_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial cost excluding TAX',
      `room_infant_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial cost',
      `room_total_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial cost excluding TAX',
      `room_total_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial cost',
      `room_rebate_cost_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
      `room_rebate_cost_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
      `room_rebate_cost_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
      `room_adult_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
      `room_adult_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost with discount excluding TAX',
      `room_adult_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost with discount',
      `room_teen_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
      `room_teen_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost with discount',
      `room_teen_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost with discount excluding TAX',
      `room_child_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
      `room_child_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost with discount',
      `room_child_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost with discount excluding TAX',
      `room_infant_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
      `room_infant_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost with discount',
      `room_infant_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost with discount excluding TAX',
      `room_total_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost with discount excluding TAX',
      `room_total_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost with discount',
      `created_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblusers',
      `created_name` varchar(25) NOT NULL DEFAULT '0' COMMENT 'username of staff who created the dossier',
      `active` smallint(1) NOT NULL DEFAULT 1 COMMENT '1 for active dossier no/ 0 for deleted',
      PRIMARY KEY (`id_booking_room_cost`),
      KEY `id_bookingfk` (`id_booking`),
      KEY `id_tour_operatorfk` (`id_tour_operator`),
      KEY `id_contractfk` (`id_contract`),
      KEY `id_hotelfk` (`id_hotel`),
      KEY `id_roomfk` (`id_room`),
      KEY `id_service_taxfk` (`id_service_tax`)
    ) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_claim_log` (
      `id_booking_room_claim_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `id_booking_room_claim` int(11) NOT NULL COMMENT 'id_booking_room_claim from booking_room_claim',
      `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
      `id_booking_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking_room from booking_room table to regroup line of accom',
      `room_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
      `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
      `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
      `room_stay_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `room_stay_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
      `id_contract` int(11) NOT NULL DEFAULT 0 COMMENT 'id_contract from tblservice_contract table',
      `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
      `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
      `id_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels_rooms table ????',
      `room_details` varchar(255) NOT NULL DEFAULT 0 COMMENT 'room choosen with occupancy and meal plan',
      `service_details` varchar(30) NOT NULL DEFAULT 'TARIFF' COMMENT 'TARIFFF = room initial tariff / OFFER = room SPO / SHARING = sharing tariff / SUPPLEMENT = additional supplement',
      `room_clients` varchar(255) NOT NULL DEFAULT '0' COMMENT 'clients in the Room',
      `room_claim_calcultation` varchar(255) NOT NULL DEFAULT 0 COMMENT 'room choosen with occupancy and meal plan',
      `room_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the room',
      `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
      `room_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
      `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of room',
      `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
      `id_claim_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from tblcurrency table',
      `room_adult_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim excluding TAX',
      `room_adult_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial claim',
      `room_teen_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim excluding TAX',
      `room_teen_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial claim',
      `room_child_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim excluding TAX',
      `room_child_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial claim',
      `room_infant_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim excluding TAX',
      `room_infant_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial claim',
      `room_total_claim_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim excluding TAX',
      `room_total_claim` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial claim',
      `room_rebate_claim_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
      `room_rebate_claim_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
      `room_rebate_claim_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
      `room_adult_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
      `room_adult_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount excluding TAX',
      `room_adult_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit claim with discount',
      `room_teen_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
      `room_teen_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount',
      `room_teen_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen claim with discount excluding TAX',
      `room_child_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
      `room_child_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount',
      `room_child_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child claim with discount excluding TAX',
      `room_infant_claim_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
      `room_infant_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount',
      `room_infant_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant claim with discount excluding TAX',
      `room_total_claim_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount excluding TAX',
      `room_total_claim_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total claim with discount',
      `room_remarks` text DEFAULT NULL COMMENT 'room for the activity booking',
      `room_internal_remarks` text DEFAULT NULL COMMENT 'room for the activity booking',
      `room_invoice_no` int(11) DEFAULT NULL COMMENT 'invoice no',
      `room_invoiced_date` date DEFAULT '9999-12-31' COMMENT 'date when the dossier will be invoiced',
      `room_close` int(11) NOT NULL DEFAULT 0 COMMENT '1 for closed dossier / 0 open',
      `room_close_on` date DEFAULT '9999-12-31' COMMENT 'date when dossier is closed',
      `room_status` varchar(25) DEFAULT 'QUOTE' COMMENT 'QUOTE,CONFIRM, CANCEL, CANCEL WITH FEE',
      `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
      `uname` varchar(45) NOT NULL DEFAULT 'NONE',
      `log_date` datetime NOT NULL DEFAULT current_timestamp(),
      `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
      PRIMARY KEY (`id_booking_room_claim_log`),
      KEY `id_booking_room_claim` (`id_booking_room_claim`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    CREATE TABLE `booking_room_cost_log` (
      `id_booking_room_cost_log` int(11) NOT NULL AUTO_INCREMENT COMMENT 'auto increment',
      `id_booking_room_cost` int(11) NOT NULL COMMENT 'id_booking_room_cost from booking_room_cost',
      `id_booking_room_claim` int(11) NOT NULL COMMENT 'id_booking_room_claim from booking_room_claim',
      `id_booking` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from client table',
      `id_booking_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id_booking_room from booking_room table to regroup line of accom',
      `room_service_paid_by` varchar(11) NOT NULL DEFAULT 'TO' COMMENT 'TO/CLIENT',
      `id_tour_operator` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbltouroperator',
      `id_client` int(11) NOT NULL DEFAULT 0 COMMENT 'id_client from client table',
      `room_stay_from` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period from',
      `room_stay_to` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Stay period to',
      `room_booking_date` date NOT NULL DEFAULT '9999-12-31' COMMENT 'Date to apply the booking',
      `id_contract` int(11) NOT NULL DEFAULT 0 COMMENT 'id_contract from tblservice_contract table',
      `id_hotel` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels table',
      `hotelname` varchar(100) DEFAULT NULL COMMENT 'hotelname from tblhotels_rooms table',
      `id_room` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tblhotels_rooms table ????',
      `room_details` varchar(255) NOT NULL DEFAULT 0 COMMENT 'room choosen with occupancy and meal plan',
      `service_details` varchar(30) NOT NULL DEFAULT 'TARIFF' COMMENT 'TARIFFF = room initial tariff / OFFER = room SPO / SHARING = sharing tariff / SUPPLEMENT = additional supplement',
      `room_clients` varchar(255) NOT NULL DEFAULT '0' COMMENT 'clients in the Room',
      `room_cost_calcultation` text DEFAULT NULL COMMENT 'room choosen with occupancy and meal plan',
      `room_adult_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of adult in the room',
      `room_teen_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of teen in the room',
      `room_child_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of child in the room',
      `room_infant_amt` int(11) NOT NULL DEFAULT 0 COMMENT 'no of infant in the room',
      `room_total_pax` int(11) NOT NULL DEFAULT 0 COMMENT 'no of pax in the room',
      `id_dept` int(11) NOT NULL DEFAULT 0 COMMENT 'id from tbldepartments',
      `room_charge` varchar(10) NOT NULL DEFAULT '' COMMENT 'PAX/UNIT',
      `id_service_tax` int(11) NOT NULL COMMENT 'id_service_tax of room',
      `tax_value` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'tax percentage charge',
      `id_cost_cur` int(11) NOT NULL DEFAULT 0 COMMENT 'id currency from tblcurrency table',
      `room_adult_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial cost excluding TAX',
      `room_adult_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit initial cost',
      `room_teen_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial cost excluding TAX',
      `room_teen_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen initial cost',
      `room_child_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial cost excluding TAX',
      `room_child_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child initial cost',
      `room_infant_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial cost excluding TAX',
      `room_infant_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant initial cost',
      `room_total_cost_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial cost excluding TAX',
      `room_total_cost` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total initial cost',
      `room_rebate_cost_type` varchar(15) DEFAULT 'None' COMMENT 'Type of rebate percentage/fixed tariff',
      `room_rebate_cost_approve_by` int(11) NOT NULL DEFAULT 0 COMMENT 'id user who approved the discount',
      `room_rebate_cost_percentage` decimal(10,2) NOT NULL DEFAULT 0.00 COMMENT 'discount percentage amount',
      `room_adult_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit discounted tariff',
      `room_adult_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost with discount excluding TAX',
      `room_adult_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'adult/unit cost with discount',
      `room_teen_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen discounted tariff',
      `room_teen_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost with discount',
      `room_teen_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'teen cost with discount excluding TAX',
      `room_child_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child discounted tariff',
      `room_child_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost with discount',
      `room_child_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'child cost with discount excluding TAX',
      `room_infant_cost_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant discounted tariff',
      `room_infant_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost with discount',
      `room_infant_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'infant cost with discount excluding TAX',
      `room_total_cost_after_rebate_exTAX` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost with discount excluding TAX',
      `room_total_cost_after_rebate` float(15,2) NOT NULL DEFAULT 0.00 COMMENT 'total cost with discount',
      `id_user` int(11) NOT NULL COMMENT 'id from tbluser',
      `uname` varchar(45) NOT NULL DEFAULT 'NONE',
      `log_date` datetime NOT NULL DEFAULT current_timestamp(),
      `log_status` varchar(15) NOT NULL COMMENT 'CREATE, UPDATE, DELETE',
      PRIMARY KEY (`id_booking_room_cost_log`),
      KEY `id_booking_room_cost` (`id_booking_room_cost`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

    ALTER TABLE `dbsolis`.`booking_room`
    ADD COLUMN `id_booking` INT(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from booking table' AFTER `id_booking_room`,
    ADD KEY `id_bookingfk` (`id_booking`);

    ALTER TABLE `dbsolis`.`booking_room_log`
    ADD COLUMN `id_booking` INT(11) NOT NULL DEFAULT 0 COMMENT 'id_booking from booking table' AFTER `id_booking_room`;
